#Opencloud API config - overrides environment variables.
os_project_domain_name:
os_project_domain_id: 
os_user_domain_name: 
os_user_domain_id:
os_project_name: 
os_project_id:
os_tenant_name: 
os_tenant_id:
os_username: 
os_password: 
os_auth_url: 
os_interface: 
os_endpoint_type: 
os_identity_api_version : 
os_region_name: 
os_auth_plugin: 

#CANARY TEST CONFIG - EXAMPLE CONFIG
#VM config - if the VM is not reachable from the host this test is run on, then a floating network will need to be configured
floating_ips: False
#floating_net_id: <floating_net_id>
pub_net_id: <pub_net_id>
#bm_net_id: <bm_net_id>
images:
  - #cirros
  - #ubuntu
ssh_users:
  - cirros
  - ubuntu
flavors:
  - #small
  - #large

#explicitly remove any services here from tempest configuration (won't run tempest tests/config on these)
services_disabled:
  - #octavia

#dev - whether local changes to submodules should be installed in containers 
dev: no

#CI 
#timing - enter the frequency with which you wish this test setup should be executed in cron format
# m h dom m dow 
schedule: "*/15 * * * *"

#DEFAULTS - no need to touch these but you can if you want
cron_lock_dir: /var/lock/cron

health_check_user: canary-agent
health_check_uid: 43000
health_check_gid: 43000
health_check_group: canary

notify_user: notify-agent
notify_uid: 43001
notify_gid: 43001
notify_group: notify

cloud_volume_name: cloud
logs_volume_name: healthmon
image_name: canary
container_name: canary
cron_image_name: cron
cron_container_name: cron
notify_image_name: notify
notify_container_name: notify

docker_runtime_directory: /var/lib/docker
dockerfile_name_canary: tempestDockerfile
dockerfile_name_cron: cronDockerfile
dockerfile_name_notify: cronDockerfile
