#Opencloud API config
os_project_domain_name: 
os_project_domain_id:
os_user_domain_name: 
os_user_domain_id:
os_project_name: 
os_project_id:
os_tenant_name: 
os_tenant_id:
os_username: 
os_password: 
os_auth_url: 
os_interface: 
os_endpoint_type: 
os_identity_api_version : 
os_region_name: 
os_auth_plugin: 

#CANARY TEST CONFIG - EXAMPLE CONFIG
#VM config - if the VM is not reachable from the host this test is run on, then a floating network will need to be configured
floating_ips: False
#floating_net_id: c75dd66e-7e1a-4b33-9240-9bc4ce452331
pub_net_id: 26023e3d-bc8e-459c-8def-dbd47ab01756
images:
  - 4b89aa64-1860-4b1e-b294-e000b1423b13
ssh_users:
  - cirros
flavors:
  - abf8401b-f0f4-4c20-bdfa-5626bca8bf31

#CANARY TEST CONFIG
# floating_ips: 
# floating_net_id: 
# pub_net_id:
# images:
# ssh_users:
# flavors:

#dev - whether docker image should be rebuilt every run of the playbook
dev: yes

#CI 
#timing - enter the frequency with which you wish this test setup should be executed in cron format
# m h dom m dow 
schedule: "* * * * *"

#DEFAULTS - no need to touch these but you can if you want
cron_lock_dir: /var/lock/cron

health_check_user: canary-agent
health_check_uid: 43000
health_check_gid: 43000
health_check_group: canary

cloud_volume_name: cloud
logs_volume_name: healthmon
image_name: canary:latest
container_name: canary
cron_image_name: cron:latest
cron_container_name: cron

docker_runtime_directory: /var/lib/docker
dockerfile_name_canary: tempestDockerfile
dockerfile_name_cron: cronDockerfile
