---
- name: Install dependencies
  hosts: localhost
  connection: local
  vars_files:
    - config.yml
  
  tasks:
  - name: uninstall docker-py if present
    become: yes
    become_method: sudo
    pip: 
      name: "docker-py"
      state: absent
    notify: 
      - uninstall docker pip #workaround since docker-py install breaks docker install - they share the same namespace

  - name: Flush handlers
    meta: flush_handlers

  - name: install docker pip
    become: yes
    become_method: sudo
    pip: 
      name: "docker"
      state: present
  
  - name: load submodules in dev mode
    shell: >
      git submodule init && git submodule update 
      && pushd tempest-fork/ && git checkout no_admin_creds && git pull && popd 
      && pushd python-tempestconf/ && git checkout master && git pull && popd 
      && pushd HealthMonitorTempestPlugin/ && git checkout main && git pull && popd
    when: dev 
      
  
  handlers:
  - name: uninstall docker pip
    become: yes
    become_method: sudo
    pip:
      name: "docker"
      state: absent
      

- name: Canary Setup
  hosts: localhost
  become: yes
  become_method: sudo
  connection: local
  vars_files:
    - config.yml
  
  tasks:
  - name: Template Dockerfile
    template:
      src: "./templates/Dockerfile.j2"
      dest: "{{ dockerfile_name_canary }}"
  - name: Build image
    docker_image:
      build:
        path: .
        dockerfile: "{{ dockerfile_name_canary }}"
      name: "{{ image_name }}"
      source: build
      force_source: "{{ dev }}"
      state: present

  - name: Create a volume for cloud config
    become: yes
    become_method: sudo
    docker_volume:
      name: "{{ cloud_volume_name }}"
      
  - name: Create a volume for logs 
    become: yes
    become_method: sudo
    docker_volume:
      name: "{{ logs_volume_name }}"

  - name: Start container
    docker_container:
      name: "{{ container_name }}"
      image: "{{ image_name }}"
      detach: yes
      tty: yes
      mounts:
        - source: "{{ cloud_volume_name }}"
          target: "/{{ cloud_volume_name }}"
        - source: "{{ logs_volume_name }}"
          target: "/var/log/{{ logs_volume_name }}"

  - name: symlink cloud volume to host
    file:
      src: "{{ docker_runtime_directory }}/volumes/{{ cloud_volume_name }}/_data"
      path: "./{{ cloud_volume_name }}"
      state: link

  - name: symlink logs volume to host
    file:
      src: "{{ docker_runtime_directory or '/var/lib/docker' }}/volumes/{{ logs_volume_name }}/_data"
      path: "/var/log/{{ logs_volume_name }}"
      state: link
  
  - name: Set OS cloud facts
    set_fact:
      os_username: "{{ os_username | default(lookup('env','OS_USERNAME'),true) }}"
      os_password: "{{ os_password | default(lookup('env','OS_PASSWORD'),true) }}"
      os_auth_url: "{{ os_auth_url | default(lookup('env','OS_AUTH_URL'),true) }}"
      os_project_domain_name: "{{ os_project_domain_name | default(lookup('env','OS_PROJECT_DOMAIN_NAME'),true) }}"
      os_project_domain_id: "{{ os_project_domain_id | default(lookup('env','OS_PROJECT_DOMAIN_ID'),true) }}"
      os_user_domain_name: "{{  os_user_domain_name | default(lookup('env','OS_USER_DOMAIN_NAME'),true)  }}"
      os_user_domain_id: "{{  os_user_domain_id | default(lookup('env','OS_USER_DOMAIN_ID'),true)  }}"
      os_project_name: "{{ os_project_name | default(lookup('env','OS_PROJECT_NAME'), true) }}"
      os_project_id: "{{ os_project_id | default(lookup('env','OS_PROJECT_ID'),true) }}"
      os_tenant_name: "{{ os_tenant_name | default(lookup('env','OS_TENANT_NAME'),true) }}"
      os_tenant_id: "{{ os_tenant_id | default(lookup('env','OS_TENANT_ID'),true) }}"
      os_interface: "{{ os_interface | default(lookup('env','OS_INTERFACE'),true) }}"
      os_endpoint_type: "{{ os_endpoint_type | default(lookup('env','OS_ENDPOINT_TYPE'),true) }}"
      os_identity_api_version : "{{ os_identity_api_version | default(lookup('env','OS_IDENTITY_API_VERSION'),true) }}"
      os_region_name: "{{ os_region_name | default(lookup('env','OS_REGION_NAME'),true) }}"
      os_auth_plugin: "{{ os_auth_plugin | default(lookup('env','OS_AUTH_PLUGIN'),true) }}"
  
  # - name: Check Keystone authentication
  #   openstack.cloud.auth:
  #     auth: {
  #       "os_username": "{{ os_username }}",
  #       "os_password": "{{ os_password }}",
  #       "os_auth_url": "{{ os_auth_url }}",
  #       "os_project_domain_name": "{{ os_project_domain_name }}",
  #       "os_project_domain_id": "{{ os_project_domain_id }}",
  #       "os_user_domain_name": "{{  os_user_domain_name }}",
  #       "os_user_domain_id": "{{  os_user_domain_id }}",
  #       "os_project_name": "{{ os_project_name }}",
  #       "os_project_id": "{{ os_project_id }}",
  #       "os_tenant_name": "{{ os_tenant_name }}",
  #       "os_tenant_id": "{{ os_tenant_id }}",
  #       "os_interface": "{{ os_interface }}",
  #       "os_endpoint_type": "{{ os_endpoint_type }}",
  #       "os_identity_api_version" : "{{ os_identity_api_version }}",
  #       "os_region_name": "{{ os_region_name }}",
  #       "os_auth_plugin": "{{ os_auth_plugin }}",
  #     }

  - name: Check minimum definitions exist
    assert:
      that:
        - pub_net_id is defined
        - pub_net_id |length
        - os_username |length
        - os_password |length
        - os_auth_url |length
      fail_msg: "Some or all of the required configuration parameters were not provided. Please source an OS RC file and/or edit 'config.yml'."


      
  - name: Configure tempest
    command: > 
      docker exec
      {{ container_name }} bash -c 
      'cd {{ cloud_volume_name }} && discover-tempest-config 
      --out /{{ cloud_volume_name }}/etc/tempest.conf --non-admin 
      --os-username {{ os_username }}
      --os-password {{ os_password }}
      --os-auth-url {{ os_auth_url }} 
      {% if os_project_domain_name |length %}
      --os-project-domain-name {{ os_project_domain_name }}
      {% endif %}
      {% if os_project_domain_id |length %}
      --os-project-domain-id {{ os_project_domain_id }}
      {% endif %}
      {% if os_user_domain_name |length %}
      --os-user-domain-name {{ os_user_domain_name }} 
      {% endif %}
      {% if os_user_domain_id |length %}
      --os-user-domain-id {{ os_user_domain_id }}
      {% endif %}
      {% if os_project_name |length %}
      --os-project-name {{ os_project_name }}
      {% endif %}
      {% if os_project_id |length %}
      --os-project-id {{ os_project_id }}
      {% endif %}
      {% if os_tenant_name |length %}
      --os-tenant-name {{ os_tenant_name }}
      {% endif %}
      {% if os_tenant_id |length %}
      --os-tenant-id {{ os_tenant_id }}
      {% endif %}
      {% if os_interface |length %}
      --os-interface {{ os_interface }}
      {% endif %}
      {% if os_endpoint_type |length %}
      --os-endpoint-override {{ os_endpoint_type }}
      {% endif %}
      {% if os_identity_api_version |length %}
      --os-api-version {{ os_identity_api_version }}
      {% endif %}
      {% if os_region_name |length %}
      --os-region-name {{ os_region_name }} 
      {% endif %}
      {% if os_auth_plugin |length %}
      --os-auth-plugin {{ os_auth_plugin }} 
      {% endif %}
      {% if floating_ips is defined and floating_ips %}
      network-feature-enabled.floating_ips {{ floating_ips }}
      {% endif %}
      {% if floating_net_id is defined and floating_net_id|length %}
      network.floating_network_name {{ floating_net_id }}
      {% endif %}
      auth.test_accounts_file /{{ cloud_volume_name }}/etc/accounts.yml
      network.public_network_id {{ pub_net_id }}'

  - name: Append tempest.conf with health monitor section header
    lineinfile:
      path: ./{{ cloud_volume_name }}/etc/tempest.conf
      line: "[healthmon]"

  - name: Append tempest.conf with test config
    blockinfile: 
      path: ./{{ cloud_volume_name }}/etc/tempest.conf
      block: |
        image = {{ item.0 }}
        ssh_user = {{ item.1 }}
        flavor = {{ item.2 }}
      marker: "# {mark} ANSIBLE MANAGED BLOCK - CONFIG {{idx+1}}"
    loop: "{{ images | zip(ssh_users, flavors) | list }}"
    loop_control:
      index_var: idx
  - name: Append tempest.conf with test config - alternative config
    blockinfile: 
      path: ./{{ cloud_volume_name }}/etc/tempest.conf
      block: |
        image_alt = {{ item.0 }}
        ssh_user_alt = {{ item.1 }}
        flavor_alt = {{ item.2 }}
      marker: "# {mark} ANSIBLE MANAGED BLOCK - ALT CONFIG {{idx+1}}"
    loop: "{{ images_alt | zip(ssh_users_alt, flavors_alt) | list }}"
    loop_control:
      index_var: idx
    when: 
      - images_alt is defined
      - ssh_users_alt is defined
      - flavors_alt is defined
  
  - name: Configure accounts.yml
    blockinfile:
      path: ./{{ cloud_volume_name }}/etc/accounts.yml
      block: |
        - username: '{{ os_username | default(lookup('env','OS_USERNAME'),true) }}'
          tenant_name: '{{ os_project_name | default(lookup('env','OS_PROJECT_NAME'),true) }}'
          password: '{{ os_password | default(lookup('env','OS_PASSWORD'),true) }}'

- name: Setup cron job to execute CI job
  hosts: localhost
  become: yes
  become_method: sudo
  connection: local
  vars_files:
    - config.yml
  
  tasks:
  - name: Template cron job
    template:
      src: ./templates/cronjob.j2
      dest: cronjob
  - name: Build cron image
    docker_image:
      build:
        path: .
        dockerfile: "{{ dockerfile_name_cron }}"
      name: "{{ cron_image_name }}"
      source: build
      state: present
  - name: Start container
    docker_container:
      name: "{{ cron_container_name }}"
      image: "{{ cron_image_name }}"
      detach: yes
      tty: yes
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock







  # - name: Append tempest.conf with images
  #   lineinfile:
  #     path: ./cloud/etc/tempest.conf
  #     line: "image = {{ item }}"
  #   loop: "{{ images }}"
  # - name: Append tempest.conf with flavors
  #   lineinfile:
  #     path: ./cloud/etc/tempest.conf
  #     line: "flavor = {{ item }}"
  #   loop: "{{ flavors }}"
  # - name: Append tempest.conf with ssh_users
  #   lineinfile:
  #     path: ./cloud/etc/tempest.conf
  #     line: "ssh_user = {{ item }}"
  #   loop: "{{ ssh_users }}"
  # - name: Append tempest.conf with images_alt
  #   lineinfile:
  #     path: ./cloud/etc/tempest.conf
  #     line: "image_alt = {{ item }}"
  #   loop: "{{ images_alt }}"
  #   when: images_alt is defined
  # - name: Append tempest.conf with flavors_alt
  #   lineinfile:
  #     path: ./cloud/etc/tempest.conf
  #     line: "flavor_alt = {{ item }}"
  #   loop: "{{ flavors_alt }}"
  #   when: flavors_alt is defined
  # - name: Append tempest.conf with ssh_users_alt
  #   lineinfile:
  #     path: ./cloud/etc/tempest.conf
  #     line: "ssh_user_alt = {{ item }}"
  #   loop: "{{ ssh_users_alt }}"
  #   when: ssh_users_alt is defined



  # - name: Add accounts.yaml for running tempest 
